### ISSUE TITLE
Does this work with Blender 2.81a?

### ISSUE THREAD

**Issue by keyle** [Linko-3D/AssetGen#13]
Simple sphere, Blender 2.81a macos, blows up "Permission denied: 'SM_Sphere.glb'"

```
Traceback (most recent call last):
  File "/Users/n/Library/Application Support/Blender/2.81/scripts/addons/AssetGen-master/GA.py", line 608, in execute
    bpy.ops.export_scene.gltf(export_format='GLB', export_selected=True, filepath=os.path.join(path, "SM_" + name))
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/addons/io_scene_gltf2/__init__.py", line 420, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 41, in save
    __write_file(json, buffer, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 135, in __write_file
    buffer)
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/addons/io_scene_gltf2/io/exp/gltf2_io_export.py", line 80, in save_gltf
    file = open(export_settings['gltf_filepath'], "wb")
PermissionError: [Errno 13] Permission denied: 'SM_Sphere.glb'

location: /Applications/Blender.app/Contents/Resources/2.81/scripts/modules/bpy/ops.py:201



location: <unknown location>:-1

```

**Comment by keyle** [comment]
File has to be saved first :)
