### ISSUE TITLE
Syntax Error crash when attempting to enable add-on

### ISSUE THREAD

**Issue by Samuel-IH** [Linko-3D/AssetGen#9]
Installing the add-on works fine, but when I try to enable it, I get this:
```
Traceback (most recent call last):
  File "/Users/somebody/Downloads/blender-2.79-macOS-10.6/blender.app/Contents/Resources/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/Users/somebody/Library/Application Support/Blender/2.79/scripts/addons/AssetGen-master-2/__init__.py", line 21
    ga_autoexportglb : bpy.props.BoolProperty(
             ^
SyntaxError: invalid syntax
```
Does AssetGen not support MacOS?

**Comment by macronomicus** [comment]
install it in Blender 2.8

**Comment by Samuel-IH** [comment]
thx it worked
